# Full Flow Pipeline
# Complete journey from plan refinement through implementation
#
# Stages:
#   1. improve-plan (3x) - Refine the plan document
#   2. elegance (1x) - Review plan for simplicity and clarity
#   3. create-tasks (1x) - Generate beads from the refined plan
#   4. refine-tasks (3x) - Polish the task definitions
#   5. ralph (25x) - Execute tasks until queue empty

name: full-flow
description: Refine plan, review for elegance, create tasks, refine tasks, execute

stages:
  - name: plan-refine
    stage: improve-plan
    runs: 3

  - name: plan-elegance
    stage: elegance
    runs: 1
    inputs:
      from: plan-refine
      select: latest

  - name: create-tasks
    stage: create-tasks
    runs: 1
    inputs:
      from: plan-elegance
      select: latest

  - name: task-refine
    stage: refine-tasks
    runs: 3
    inputs:
      from: create-tasks
      select: latest

  - name: work
    stage: ralph
    runs: 25
    inputs:
      from: task-refine
      select: latest
